export default {
    UPDATE: 'UPDATE',
    ROTATE_LEFT: 'ROTATE_LEFT',
    ROTATE_RIGHT: 'ROTATE_RIGHT',
    DROP_THE_BLOCK: 'DROP_THE_BLOCK',
    PAUSE: 'PAUSE',
    RESUME: 'RESUME',
    RESTART: 'RESTART'
}