export default {
    UPDATE: 'UPDATE',
    ROTATE_LEFT: 'ROTATE_LEFT',
    ROTATE_RIGHT: 'ROTATE_RIGHT',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    DROP: 'DROP',
    PAUSE: 'PAUSE',
    RESUME: 'RESUME',
    RESTART: 'RESTART'
}